### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
	"username": "root",
	"password": "123456"
}

### Protected (me)
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290IiwianRpIjoiN2M4NzI4ZGQ2RjOC00ZWQxLWEyMjAtNmM1ZDJlMDNhMGIxIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJpYXQiOjE3NjMzODQxODMsImV4cCI6MTc2MzM4NDc4M30.9Pu8nLx8PUL16A_zChIc-jqskKQFERWvNcpfqcsr2WQ

### Refresh (cookie auto-sent by browser)
POST http://localhost:8080/api/auth/refresh

### Logout
POST http://localhost:8080/api/auth/logout


