### Get customer accounts (ADMIN, with search)
GET http://localhost:8080/api/accounts/customers?page=0&size=10&q=user
Authorization: Bearer {{ACCESS_TOKEN}}

# Response 200
# {
#   "message": "Customer account list",
#   "data": [
#     {
#       "id": 10,
#       "username": "user1",
#       "email": "user1@example.com",
#       "displayName": "User 1",
#       "roleName": "USER",
#       "fullName": null,
#       "phone": null
#     }
#   ],
#   "meta": { "page": 0, "size": 10, "total": 1 },
#   "error": null
# }
#
### Edit customer account (ADMIN)
PUT http://localhost:8080/api/accounts/customers/1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
	"email": "customer1+new@example.com",
	"displayName": "Customer 1 New"
}

# Response 200
# {
#   "message": "Update customer account successfully",
#   "data": {
#     "id": 10,
#     "username": "user1",
#     "email": "customer1+new@example.com",
#     "displayName": "Customer 1 New",
#     "roleName": "USER"
#   },
#   "meta": null,
#   "error": null
# }
#
### Delete customer account (ADMIN)
DELETE http://localhost:8080/api/accounts/customers/1
Authorization: Bearer {{ACCESS_TOKEN}}

# Response 200
# {
#   "message": "Delete customer account successfully",
#   "data": null,
#   "meta": null,
#   "error": null
# }


