-- PostgreSQL initial schema for Apartment app
-- Tables follow the provided DB design with NO CASCADE behavior (default NO ACTION)

-- ===== User and Role =====
CREATE TABLE role (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INTEGER NOT NULL,
    display_name VARCHAR(255) NULL,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    email_verified_at TIMESTAMP NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES role(role_id)
);
CREATE INDEX idx_users_role_id ON users(role_id);

-- ===== File (path only) =====
CREATE TABLE files (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

-- ===== Start Property =====
-- Define
CREATE TABLE property_sale_info (
    user_id BIGINT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_sale_info_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE property_area (
    area_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_name VARCHAR(255) NOT NULL UNIQUE,
    area_link VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE property_type (
    type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE property_define_details (
    detail_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detail_name VARCHAR(255) NOT NULL UNIQUE,
    is_number BOOLEAN NOT NULL DEFAULT FALSE,
    unit VARCHAR(50) NULL,
    show_in_home_page BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

-- Property
CREATE TABLE property (
    property_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    description TEXT NULL,
    type_id INTEGER NOT NULL,
    sale_id BIGINT NOT NULL,
    area_id INTEGER NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_property_type FOREIGN KEY (type_id) REFERENCES property_type(type_id),
    CONSTRAINT fk_property_sale FOREIGN KEY (sale_id) REFERENCES property_sale_info(user_id),
    CONSTRAINT fk_property_area FOREIGN KEY (area_id) REFERENCES property_area(area_id)
);
CREATE INDEX idx_property_type_id ON property(type_id);
CREATE INDEX idx_property_sale_id ON property(sale_id);
CREATE INDEX idx_property_area_id ON property(area_id);
CREATE INDEX idx_property_is_public ON property(is_public);

-- Dependent
CREATE TABLE property_gallery (
    property_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_gallery_property FOREIGN KEY (property_id) REFERENCES property(property_id),
    CONSTRAINT fk_gallery_file FOREIGN KEY (file_id) REFERENCES files(file_id),
    CONSTRAINT pk_property_gallery PRIMARY KEY (property_id, file_id)
);
CREATE INDEX idx_property_gallery_property_id ON property_gallery(property_id);
CREATE INDEX idx_property_gallery_file_id ON property_gallery(file_id);

CREATE TABLE property_details (
    detail_id INTEGER NOT NULL,
    property_id BIGINT NOT NULL,
    value TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_details_detail FOREIGN KEY (detail_id) REFERENCES property_define_details(detail_id),
    CONSTRAINT fk_details_property FOREIGN KEY (property_id) REFERENCES property(property_id),
    CONSTRAINT pk_property_details PRIMARY KEY (detail_id, property_id)
);
CREATE INDEX idx_property_details_property_id ON property_details(property_id);
CREATE INDEX idx_property_details_detail_id ON property_details(detail_id);


