package com.qvinh.apartment.shared.error;

public enum ErrorCode {
	VALIDATION_ERROR,
	UNAUTHORIZED,
	FORBIDDEN,
	MALFORMED_JSON,
	INTERNAL_ERROR,
	SERVICE_UNAVAILABLE,

	RESOURCE_NOT_FOUND,
	USER_NOT_FOUND,
	FILE_NOT_FOUND,
	FILE_VARIANT_NOT_FOUND,
	PROPERTY_NOT_FOUND,
	PROPERTY_TYPE_NOT_FOUND,
	PROPERTY_AREA_NOT_FOUND,
	PROPERTY_SALE_INFO_NOT_FOUND,
	PROPERTY_GALLERY_NOT_FOUND,
	PROPERTY_DEFINE_DETAIL_NOT_FOUND,
	PROPERTY_DETAIL_NOT_FOUND,
	ROLE_NOT_FOUND,

	RESOURCE_CONFLICT,
	USERNAME_ALREADY_EXISTS,
	EMAIL_ALREADY_EXISTS,
	FILE_ALREADY_IN_GALLERY,
	PROPERTY_DETAILS_CONFLICT,
	BUSINESS_ERROR
}
